#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Invalid argument count"
	exit
fi

LOGIN=$1
LENGTH=20
PASSWORD_FILE=logins
USER_HOME=/home/warehouse/user/$LOGIN
SSH_DIRECTORY=$USER_HOME/.ssh
ORIGINAL_DOWNLOAD_DIRECTORY=/home/void/torrent/complete
USER_DOWNLOAD_DIRECTORY=$USER_HOME/all
USER_FILTERED_DIRECTORY=$USER_HOME/filtered
SHELL_GROUP=warehouse-shell

echo -n $LOGIN":">$PASSWORD_FILE
ruby password.rb $LENGTH>>$PASSWORD_FILE
useradd -M -N -g $SHELL_GROUP -s /usr/bin/warehouse-shell -d $USER_HOME $LOGIN
mkdir $USER_HOME
mkdir $SSH_DIRECTORY
chown $LOGIN:$SHELL_GROUP $SSH_DIRECTORY
mkdir $USER_DOWNLOAD_DIRECTORY
mount --bind -o ro $ORIGINAL_DOWNLOAD_DIRECTORY $USER_DOWNLOAD_DIRECTORY
mkdir $USER_FILTERED_DIRECTORY
chmod 775 $USER_FILTERED_DIRECTORY
chown $LOGIN:$SHELL_GROUP $USER_FILTERED_DIRECTORY
cat $PASSWORD_FILE
chpasswd < $PASSWORD_FILE
rm $PASSWORD_FILE
