#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Invalid argument count"
	exit
fi

LOGIN=$1
SFTP_LOGIN=$1-sftp
LENGTH=20
PASSWORD_FILE=logins
USER_HOME=/home/warehouse/user/$LOGIN
SSH_DIRECTORY=$USER_HOME/.ssh
SHELL_GROUP = warehouse-shell
SFTP_GROUP = warehouse-sftp

echo -n $LOGIN":">$PASSWORD_FILE
ruby password.rb $LENGTH>>$PASSWORD_FILE
echo -n $SFTP_LOGIN":">>$PASSWORD_FILE
ruby password.rb $LENGTH>>$PASSWORD_FILE
useradd -M -N -g $SHELL_GROUP -s /bin/warehouse-shell -d $USER_HOME $LOGIN
useradd -M -N -g $SFTP_GROUP -s /bin/false -d $USER_HOME $SFTP_LOGIN
mkdir $USER_HOME
mkdir $SSH_DIRECTORY
chown $LOGIN:$SHELL_GROUP $SSH_DIRECTORY
cat $PASSWORD_FILE
chpasswd < $PASSWORD_FILE
rm $PASSWORD_FILE
