#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Invalid argument count"
	exit
fi

LOGIN=$1
SFTP_LOGIN=$1-sftp
LENGTH=20
PASSWORD_FILE=logins
USER_HOME=/home/scene/user/$LOGIN

echo -n $LOGIN":">$PASSWORD_FILE
ruby password.rb $LENGTH>>$PASSWORD_FILE
echo -n $SFTP_LOGIN":">>$PASSWORD_FILE
ruby password.rb $LENGTH>>$PASSWORD_FILE
mkdir $USER_HOME
chown $LOGIN:scene-shell $USER_HOME
useradd -M -N -G scene-shell -s /bin/scene-shell -d $USER_HOME $LOGIN
useradd -M -N -G scene-sftp -s /usr/lib/sftp-server -d $USER_HOME $SFTP_LOGIN
cat $PASSWORD_FILE
chpasswd < $PASSWORD_FILE
rm $PASSWORD_FILE
